apiVersion: v1
kind: Secret
metadata:
  name: avatar-secrets
  labels:
    app: avatar-service
type: Opaque
data:
  DB_PASSWORD: <base64-encoded>
  S3_ACCESS_KEY: <base64-encoded>
  S3_SECRET_KEY: <base64-encoded>
  RMQ_URL: <base64-encoded>
