{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "avatar-service.fullname" . }}-secrets
  labels:
    {{- include "avatar-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.databaseUrl }}
  DATABASE_URL: {{ .Values.secrets.databaseUrl }}
  {{- end }}
  {{- if .Values.secrets.dbPassword }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword }}
  {{- end }}
  {{- if .Values.secrets.s3AccessKey }}
  S3_ACCESS_KEY: {{ .Values.secrets.s3AccessKey }}
  {{- end }}
  {{- if .Values.secrets.s3SecretKey }}
  S3_SECRET_KEY: {{ .Values.secrets.s3SecretKey }}
  {{- end }}
  {{- if .Values.secrets.rabbitmqUrl }}
  RMQ_URL: {{ .Values.secrets.rabbitmqUrl }}
  {{- end }}
{{- end }}
