apiVersion: v1
kind: Service
metadata:
  name: {{ include "avatar-service.fullname" . }}
  labels:
    {{- include "avatar-service.labels" . | nindent 4 }}
    app: avatar-service
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "avatar-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
